# Generated by Django 3.1 on 2020-09-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odo_correction', '0003_auto_20200828_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='excel',
            name='corrected',
            field=models.BooleanField(default=False),
        ),
    ]
