# Generated by Django 3.1 on 2020-09-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odo_correction', '0004_excel_corrected'),
    ]

    operations = [
        migrations.AddField(
            model_name='excel',
            name='file_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='excel',
            name='file_end',
            field=models.BooleanField(default=False),
        ),
    ]
