# Generated by Django 3.1 on 2020-09-03 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odo_correction', '0005_auto_20200903_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excel',
            name='file_end',
        ),
    ]
